### PR TITLE
feat: add compatibility for PHP 8.2

### PR DESCRIPTION
**Pull request by i-derevianko**

### CODE REVIEW

**Comment by marcosmarcolin** [comment]
Hello @i-derevianko,  firstly, thank you for your PR!

The user tested previous versions and confirmed that the code worked correctly.

What was the error that prompted the PR? Undefined properties?

LGTM.

@walkor Do you agree?

**Review by marcosmarcolin — APPROVED** [review]

**Comment by i-derevianko** [comment]
Hi @marcosmarcolin!
Yeah, undefined properties mostly, and problem with the parent class calling.

**Comment by i-derevianko** [comment]
@marcosmarcolin @walkor 

Found some problem there is differences in release v2.0.3 and repo. 

For example https://github.com/walkor/phpsocket.io/blob/master/src/Engine/Socket.php#L24

There is 
`
    public $upgradeTransport = null;
    public $transport = null;
`

But there is no this attributes in release v2.0.3. Check it please before merge.

**Comment by marcosmarcolin** [comment]
@i-derevianko 

Yes, after version 2.0.3 there were changes to the code, but a version was not released.

We can see all the changes after the mentioned version here: https://github.com/walkor/phpsocket.io/compare/v2.0.3...master

All changes should go into the next version.

**Comment by walkor** [comment]
@i-derevianko 
Thank you for your PR.

@marcosmarcolin 
That great , thank you for your release.

**Comment by marcosmarcolin** [comment]
Thanks @i-derevianko!

Released v2.1.0

**Pull request merged**
